# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
    # You can also specify other tool versions:
    install:
    - method: pip
      path: .
      
sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true

formats:
  - pdf
  - epub
