[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Spacehub"
authors = [{name = "Togtuunbayar", email = "spacehub13@gmail.com"}]
dynamic = ["version", "description"]
